2022-08-17 13:00:59,167 INFO    MainThread:1352419 [wandb_setup.py:_flush():76] Configure stats pid to 1352419
2022-08-17 13:00:59,167 INFO    MainThread:1352419 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2022-08-17 13:00:59,167 INFO    MainThread:1352419 [wandb_setup.py:_flush():76] Loading settings from /home/compu/jh/project/colon_compare/scripts/logs/evaluations/runs/prostate/voting/vit_large_r50_s32_384/2022-08-17_13-00-06/wandb/settings
2022-08-17 13:00:59,167 INFO    MainThread:1352419 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True'}
2022-08-17 13:00:59,167 WARNING MainThread:1352419 [wandb_setup.py:_flush():76] Could not find program at ../test.py
2022-08-17 13:00:59,167 INFO    MainThread:1352419 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../test.py'}
2022-08-17 13:00:59,167 INFO    MainThread:1352419 [wandb_init.py:_log_setup():461] Logging user logs to ./wandb/run-20220817_130059-20b6vjl2/logs/debug.log
2022-08-17 13:00:59,168 INFO    MainThread:1352419 [wandb_init.py:_log_setup():462] Logging internal logs to ./wandb/run-20220817_130059-20b6vjl2/logs/debug-internal.log
2022-08-17 13:00:59,168 INFO    MainThread:1352419 [wandb_init.py:init():495] calling init triggers
2022-08-17 13:00:59,168 INFO    MainThread:1352419 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-08-17 13:00:59,168 INFO    MainThread:1352419 [wandb_init.py:init():548] starting backend
2022-08-17 13:00:59,168 INFO    MainThread:1352419 [wandb_init.py:init():552] setting up manager
2022-08-17 13:00:59,172 INFO    MainThread:1352419 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-17 13:00:59,178 INFO    MainThread:1352419 [wandb_init.py:init():558] backend started and connected
2022-08-17 13:00:59,183 INFO    MainThread:1352419 [wandb_init.py:init():636] updated telemetry
2022-08-17 13:00:59,304 INFO    MainThread:1352419 [wandb_init.py:init():667] communicating run to backend with 30 second timeout
2022-08-17 13:01:00,075 INFO    MainThread:1352419 [wandb_run.py:_on_init():1982] communicating current version
2022-08-17 13:01:00,136 INFO    MainThread:1352419 [wandb_run.py:_on_init():1986] got version response 
2022-08-17 13:01:00,136 INFO    MainThread:1352419 [wandb_init.py:init():700] starting run threads in backend
2022-08-17 13:01:00,591 INFO    MainThread:1352419 [wandb_run.py:_console_start():1962] atexit reg
2022-08-17 13:01:00,591 INFO    MainThread:1352419 [wandb_run.py:_redirect():1820] redirect: SettingsConsole.WRAP_RAW
2022-08-17 13:01:00,592 INFO    MainThread:1352419 [wandb_run.py:_redirect():1885] Wrapping output streams.
2022-08-17 13:01:00,592 INFO    MainThread:1352419 [wandb_run.py:_redirect():1907] Redirects installed.
2022-08-17 13:01:00,594 INFO    MainThread:1352419 [wandb_init.py:init():732] run started, returning control to user process
2022-08-17 13:01:00,603 INFO    MainThread:1352419 [wandb_run.py:_config_callback():1152] config_cb None None {'ckpt_path': '/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/prostate/classifycompare/2022-08-09_10-34-32/checkpoints/epoch_005.ckpt'}
2022-08-17 13:12:01,055 ERROR   MainThread:1352419 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 330, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/internal_api.py", line 204, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)
2022-08-17 13:13:55,551 INFO    MainThread:1352419 [wandb_run.py:_finish():1728] finishing run ozoooooh/prostate/20b6vjl2
2022-08-17 13:13:55,551 INFO    MainThread:1352419 [wandb_run.py:_atexit_cleanup():1931] got exitcode: 0
2022-08-17 13:13:55,551 INFO    MainThread:1352419 [wandb_run.py:_restore():1914] restore
2022-08-17 13:13:55,551 INFO    MainThread:1352419 [wandb_run.py:_restore():1920] restore done
2022-08-17 13:14:00,552 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:14:05,653 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:14:10,754 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:14:15,855 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:14:20,956 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:14:26,057 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:14:31,158 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:14:36,259 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:14:41,360 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:14:46,462 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:14:51,563 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:14:56,664 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:15:01,765 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:15:06,866 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:15:11,969 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:15:17,070 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:15:22,171 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:15:27,272 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:15:32,373 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:15:37,475 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:15:42,576 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:15:47,677 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:15:52,779 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:15:57,882 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:16:02,983 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:16:08,084 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:16:13,185 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:16:18,286 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:16:23,387 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:16:28,488 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-17 13:16:29,794 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 32019
  total_bytes: 32019
}

2022-08-17 13:16:30,387 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 32019
  total_bytes: 32019
}

2022-08-17 13:16:30,902 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 32019
  total_bytes: 32019
}

2022-08-17 13:16:32,200 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 32019
  total_bytes: 32019
}

2022-08-17 13:16:32,757 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 32019
  total_bytes: 44550
}

2022-08-17 13:16:32,860 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 32019
  total_bytes: 44550
}

2022-08-17 13:16:32,963 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 32019
  total_bytes: 44550
}

2022-08-17 13:16:33,064 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 32019
  total_bytes: 44550
}

2022-08-17 13:16:33,166 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 32019
  total_bytes: 44550
}

2022-08-17 13:16:33,268 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 38004
  total_bytes: 44550
}

2022-08-17 13:16:33,371 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 40282
  total_bytes: 44550
}

2022-08-17 13:16:33,473 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 40282
  total_bytes: 44550
}

2022-08-17 13:16:33,576 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 44550
  total_bytes: 44550
}

2022-08-17 13:16:33,679 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 44550
  total_bytes: 44550
}

2022-08-17 13:16:33,782 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 44550
  total_bytes: 44550
}

2022-08-17 13:16:33,884 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 44550
  total_bytes: 44550
}

2022-08-17 13:16:33,987 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 44550
  total_bytes: 44550
}

2022-08-17 13:16:34,742 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 44550
  total_bytes: 44550
}

2022-08-17 13:16:35,405 INFO    MainThread:1352419 [wandb_run.py:_on_finish():2221] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 44550
  total_bytes: 44550
}
local_info {
}

2022-08-17 13:16:36,512 INFO    MainThread:1352419 [wandb_run.py:_footer_history_summary_info():3305] rendering history
2022-08-17 13:16:36,513 INFO    MainThread:1352419 [wandb_run.py:_footer_history_summary_info():3337] rendering summary
2022-08-17 13:16:36,515 INFO    MainThread:1352419 [wandb_run.py:_footer_sync_info():3261] logging synced files
